name: Process order
on:
  issues:
    types: opened
concurrency: 'main'
jobs:
  place_order:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/order-pizza.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > order.json

      - run: cat order.json

      - run: node ./place-order.js

      - name: Commit changes
        shell: bash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]" && \
          git add README.md && \
          git commit -m 'Place order' && \
          git push

      - uses: peter-evans/close-issue@v1
        with:
          comment: Pizza time! Check out the <a href="../">README</a>.
